// <auto-generated />
using CodePropertyGraph.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodePropertyGraph.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.CodeElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectoryId")
                        .HasColumnType("int");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAbstract")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSealed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LayerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NamespaceId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryId");

                    b.HasIndex("LayerId");

                    b.HasIndex("NamespaceId");

                    b.HasIndex("ProjectId");

                    b.ToTable("CodeElement", (string)null);
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.Directory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Directory", (string)null);
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.ElementDependency", b =>
                {
                    b.Property<int>("SourceElementId")
                        .HasColumnType("int");

                    b.Property<int>("TargetElementId")
                        .HasColumnType("int");

                    b.Property<string>("DependencyType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDirect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("SourceElementId", "TargetElementId", "DependencyType");

                    b.HasIndex("TargetElementId");

                    b.ToTable("ElementDependency", (string)null);
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.ElementImplementation", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("InterfaceId")
                        .HasColumnType("int");

                    b.HasKey("ClassId", "InterfaceId");

                    b.HasIndex("InterfaceId");

                    b.ToTable("ElementImplementation", (string)null);
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.Layer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Layer", (string)null);
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.Namespace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.ToTable("Namespace", (string)null);
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.CodeElement", b =>
                {
                    b.HasOne("CodePropertyGraph.Domain.Entities.Directory", "Directory")
                        .WithMany("CodeElements")
                        .HasForeignKey("DirectoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodePropertyGraph.Domain.Entities.Layer", "Layer")
                        .WithMany("CodeElements")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodePropertyGraph.Domain.Entities.Namespace", "Namespace")
                        .WithMany("CodeElements")
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodePropertyGraph.Domain.Entities.Project", "Project")
                        .WithMany("CodeElements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Directory");

                    b.Navigation("Layer");

                    b.Navigation("Namespace");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.ElementDependency", b =>
                {
                    b.HasOne("CodePropertyGraph.Domain.Entities.CodeElement", "SourceElement")
                        .WithMany("OutboundDependencies")
                        .HasForeignKey("SourceElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodePropertyGraph.Domain.Entities.CodeElement", "TargetElement")
                        .WithMany("InboundDependencies")
                        .HasForeignKey("TargetElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceElement");

                    b.Navigation("TargetElement");
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.ElementImplementation", b =>
                {
                    b.HasOne("CodePropertyGraph.Domain.Entities.CodeElement", "Class")
                        .WithMany("Implementations")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodePropertyGraph.Domain.Entities.CodeElement", "Interface")
                        .WithMany()
                        .HasForeignKey("InterfaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Interface");
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.CodeElement", b =>
                {
                    b.Navigation("Implementations");

                    b.Navigation("InboundDependencies");

                    b.Navigation("OutboundDependencies");
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.Directory", b =>
                {
                    b.Navigation("CodeElements");
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.Layer", b =>
                {
                    b.Navigation("CodeElements");
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.Namespace", b =>
                {
                    b.Navigation("CodeElements");
                });

            modelBuilder.Entity("CodePropertyGraph.Domain.Entities.Project", b =>
                {
                    b.Navigation("CodeElements");
                });
#pragma warning restore 612, 618
        }
    }
}
